### ISSUE TITLE
Evaluate ninja generator

### ISSUE THREAD

**Issue by psakievich** [sandialabs/spack-manager#1]
Had some problems with ninja generator for cuda builds when I change `TMP_DIR`
Also would like to test it with `nalu-wind-nightly` to make sure all the logic is there

**Comment by tasmith4** [comment]
@psakievich +1 for ninja -- I've come to strongly prefer it to regular make.  I'm curious under what conditions you have issues with ninja when changing `TMPDIR`?  I regularly build Trilinos for cuda with ninja on ascicgpu030, changing `TMPDIR` as part of my environment setup, and I haven't seen any issues with that.

**Comment by psakievich** [comment]
@tasmith4 this was a pretty old issue. That I was going to circle back to. I did a cuda build on ascicgpu24 last week using `ninja` since @jrood-nrel added it back and it worked well so I'm going to close this issue.  If you use `nalu-wind-developer` ninja will be the generator it uses.
