### ISSUE TITLE
create_machine_spack_environment.py can't find "find_machine"

### ISSUE THREAD

**Issue by ndevelder** [sandialabs/spack-manager#157]
Maybe this is something I did, but "find_machine" python script isn't showing up for "create_machine_spack_environment.py"...or anywhere else I can find? Commenting out the import command and using "-m" with the machine designation from the "configs" directory gets around this.

**Comment by psakievich** [comment]
Updating here.  This script should be removed.  `spack manager crete-env` is the replacement for this script.  I will remove this script.
