### ISSUE TITLE
quick-* commands add text to prompt

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#165]
Is it possible for the `quick-*` commands to not add text to the prompt by default?  I've discovered it doesn't play well with my custom prompt.

**Comment by psakievich** [comment]
I personally like it on. But I can give you a way to default it off in your instance through an environment variable?

**Comment by tasmith4** [comment]
Or is there an easy way to get rid of it and go back to what I had without killing the shell?  Pretty much guaranteed I'll forget to set the magic environment variable, unless I happen to have saved it in a script (which defeats the purpose of the `quick-*` commands), and it seems like the modified prompt stays around forever once it's initialized?

**Comment by psakievich** [comment]
@tasmith4 I was just thinking I'd add an environment variable `SPACK_MANAGER_NO_PROMPT` which you can set in your bash_profile so you don't forget it? If the environment variable exists then these commands will execute without the prompt

**Comment by psakievich** [comment]
actually it looks like `export PS1=$SPACK_OLD_PS1` will remove the prompt. I can just add a shortcut to remove the prompt in the `useful_bash_functions.sh` if that works for you

**Comment by tasmith4** [comment]
That would make me happier.  I was hoping to avoid putting any spack-manager-related things in my bash_profile.

**Comment by psakievich** [comment]
okay I'll push that tonight

**Comment by psakievich** [comment]
FWIW I just wrap all my spack-manager stuff into a bash function so it doesn't live in my shell unless I call the function.  3-4 lines live in my bash_profile as a function, but that's all.  I don't like having this in my shell unless I'm using it either.
I guess any config stuff could live in whatever script/profile you use to activate spack-manager.
