### ISSUE TITLE
Build failure on ascicgpu

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#179]
On ascicgpu057, I was trying to build the full stack with the clingo concretizer (i.e. no externals) as follows:
```
$ cd /scratch/tasmit/spack-manager-test                           # empty directory
$ git clone --recursive git@github.com:psakievich/spack-manager   # checked out 9c2fd5e
$ export SPACK_MANAGER=$(pwd)/spack-manager
$ source $SPACK_MANAGER/scripts/useful_bash_functions.sh
$ quick-create-dev -s nalu-wind@master
$ spack install
```

This fails with numerous errors in the TPL builds, e.g. libsigsegv:
```
  >> 1714    /tmp/cczmYN1T.s:1123: Error: unknown .loc sub-directive `view'
  >> 1715    /tmp/cczmYN1T.s:1123: Error: unknown pseudo-op: `.lvu378'
```
and also readline, which fails with numerous compile errors, e.g.
```
     368    In file included from vi_mode.c:35:
  >> 369    ./config.h:30:17: error: two or more data types in declaration specifiers
     370       30 | #define ssize_t int
     371          |                 ^~~
     372    In file included from funmap.c:25:
  >> 373    ./config.h:28:16: error: duplicate 'unsigned'
     374       28 | #define size_t unsigned int
     375          |                ^~~~~~~~
```

@psakievich is it possible this is an issue with the compilers you recently installed?

**Comment by psakievich** [comment]
@tasmith4 I've reproduced this.  I think it is due to the different cpu's here vs on ascicgpu22.  I compiled the compiler for a general architecture.

**Comment by psakievich** [comment]
looks like it's a binutils thing: https://bugzilla.redhat.com/show_bug.cgi?id=1552529

**Comment by psakievich** [comment]
so we are using an older version of binutils in the environment.  I've got an updated build of it so I'm going to figure out how to turn that on

**Comment by psakievich** [comment]
@tasmith4 does this set of commands work for you on ascicgpu22 just not 057?

**Comment by tasmith4** [comment]
No, I get this instead:
```
$ quick-create-dev -s nalu-wind@master
+ spack-start
==> Removing cached information on repositories
==> Error: invalid syntax (create_dev_env.py, line 18)
+ spack manager create-dev-env -s nalu-wind@master
==> Error: invalid syntax (create_dev_env.py, line 18)

ERROR: Exiting quick-create prematurely
```

I'll note though, that I don't really have anything setup on 22, I only go over there if I absolutely need to reproduce something on that machine, so it's not ultimately that helpful to my day-to-day workflow if it works on 22 but not 057.

**Comment by psakievich** [comment]
I'd like you to do it for a reproducer if you can.  I don't see the problem on 22, but I have lots of stuff already installed.  This could be a subtle thing about ld where we need to cary one built for each architecture.  Or you could ask Dong Hun to try it out if he develops on 22.
Also just to confirm, is gcc8 is still working on 057?  I may just switch everything back to devtoolsets if that's the case and use the devtoolset-9

**Comment by tasmith4** [comment]
happy to do a reproducer, but how do I get past the syntax error?
