### ISSUE TITLE
Need a spec to turn off Cuda UVM

### ISSUE THREAD

**Issue by ldh4** [sandialabs/spack-manager#185]
I would like to be able to turn off UVM for Cuda builds with something like:

`exawind+hypre ^nalu-wind ^trilinos~cuda_uvm`

**Comment by psakievich** [comment]
@ldh4 updating spack will turn off UVM for trilinos.  Is this sufficient or should we add a switch to turn it off?
https://github.com/spack/spack/commit/3a4ab5f96f7c34007b3bcc261cc4218704dd8b55

**Comment by tasmith4** [comment]
@psakievich it's more correct to add a "cuda_uvm" option to the Trilinos package (I'm surprised that wasn't already there).  Nalu-Wind currently heavily relies on UVM -- we're working on that on STK team, so we want to be able to turn it off to build and find the bugs.  But turning UVM off by default will break Nalu-Wind Cuda builds and runs, so I think it's not the right time to turn it off by default in spack-manager.

**Comment by psakievich** [comment]
@tasmith4 ah yes that is right. I will put a PR for this into spack today.
