### ISSUE TITLE
Confusing phrase in docs

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#193]
The developer tutorial contains the sentence "You may also wonder why we are using `nalu-wind` instead of `nalu-wind`".  I believe one or both of these specs has a typo, but am unsure what the original intent was.

**Comment by psakievich** [comment]
@jrood-nrel I think this is a remnant of when we had `nalu-wind-developer` as a package? Is that right?
https://github.com/psakievich/spack-manager/blob/992fcb5def2c963ba7d5fc48b1e26f92eb0515ad/docs/user_profiles/developers/developer_tutorial.md?plain=1#L110
I think we can just delete this line unless you meant something else.

**Comment by psakievich** [comment]
Removed this file
