### ISSUE TITLE
nvcc_wrapper not picked up in builds with externals on ascicgpu

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#209]
After `quick-develop -n develop -s 'nalu-wind@master+cuda cuda_arch=70' trilinos@develop`, `spack install` produces errors like this during the `nalu-wind` build:
```
g++: error: unrecognized command line option '--relocatable-device-code=true'
```
Also, one of the build lines shows that spack is building with `mpic++`, not `nvcc_wrapper`:
```
/projects/wind/system-spack/opt/spack/linux-rhel7-x86_64/gcc-9.3.0/mpich-3.4.2-4h2muy6jlgfdahehxmxa4ybndfdb6gx2/bin/mpic++ -DUSE_STK_SIMD_NONE -I/scratch/tasmit/spack-manager-test/spack-manager/environments/develop/nalu-wind/include -I/scratch/tasmit/spack-manager-test/spack-manager/environments/develop/nalu-wind/spack-build-khf4ao2/include -isystem /scratch/tasmit/spack-manager-test/spack-manager/spack/opt/spack/linux-rhel7-x86_64/gcc-9.3.0/trilinos-developjeus3vtaczns5wytutya65qwntxa5yvf/include -isystem /projects/wind/spack-manager/views/exawind/snapshots/ascicgpu/2022-02-14/gcc-cuda/include -isystem /projects/wind/system-spack/opt/spack/linux-rhel7-x86_64/gcc-9.3.0/cuda-11.2.2-wlah7an4q7rej4uylqlimczaa6z3zlq7/include -isystem /projects/wind/spack-manager/views/exawind/snapshots/ascicgpu/2022-02-14/gcc-cuda/lib/cmake/yaml-cpp/../../../include -O3 -DNDEBUG -fPIC --relocatable-device-code=true -expt-extended-lambda -Wext-lambda-captures-this -arch=sm_70 --expt-relaxed-constexpr -Wall -Wextra -pedantic -faligned-new -std=c++14 -MD -MT CMakeFiles/nalu.dir/src/AssemblePNGElemSolverAlgorithm.C.o -MF CMakeFiles/nalu.dir/src/AssemblePNGElemSolverAlgorithm.C.o.d -o CMakeFiles/nalu.dir/src/AssemblePNGElemSolverAlgorithm.C.o -c /scratch/tasmit/spack-manager-test/spack-manager/environments/develop/nalu-wind/src/AssemblePNGElemSolverAlgorithm.C
```

However, after `quick-create-dev -n create-dev -s 'nalu-wind@master+cuda cuda_arch=70' trilinos@develop`, `spack install` succeeds.  I've verified this behavior on `ascicgpu057`, and @ldh4 has also reported it on `ascicgpu22`, so it seems to not be machine-specific.  Based on the fact that `quick-develop` fails while `quick-create-dev` succeeds, my initial assessment is that something is broken with the `ascicgpu` externals.

@psakievich we are getting successful builds without externals, so this is not urgent, but wanted you to be aware.

**Comment by psakievich** [comment]
@tasmith4 thanks for logging this. We will look into this. It looks like it could be an issue with spack's infrastructure that they are addressing. For now let's just have the stk team use `quick-create-dev` and skip the externals.
