### ISSUE TITLE
trap command keeps ascicgpu from reporting results to CDash

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#242]
The ascicgpu platform has been consistently unreliable in reporting results to CDash (usually failing to report), even though it consistently reports successfully installing/running the nightly test package.

Yesterday and today, I ran the nightly scripts multiple times, each time they failed to report until I commented out the trap command at the beginning of `exawind-tests-script.sh`:

https://github.com/psakievich/spack-manager/blob/aada732cb3e2a311d8c97af25e464a087932be8b/scripts/run-exawind-nightly-tests.sh#L34

While I don't really understand what this command is doing, I suspect it is somehow killing whatever process is reporting to the dashboard.

@jrood-nrel @psakievich what's the best path forward here?  The easiest path is to simply delete that line, but I suspect it exists for a reason -- what was the original motivation for putting it in?  Do we need to make this line platform-specific?

**Comment by psakievich** [comment]
The trap command is so you can launch multiple concurrent instances of `spack install` to parallelize building at the DAG level. It ensures that everything gets killed if there is an error. But what I suspect is going on is a build error could be triggering the trap and killing cdash reporting too?

I think the simplest thing would be to put a conditional on the command based on the SPACK_MANAGER_MACHINE so it can be omitted by ascicgpu.

**Comment by tasmith4** [comment]
@psakievich so that's why the loop here?

https://github.com/psakievich/spack-manager/blob/aada732cb3e2a311d8c97af25e464a087932be8b/scripts/run-exawind-nightly-tests.sh#L98

**Comment by tasmith4** [comment]
also @psakievich I did a spot-check and the following line appears four times in the log for a run that didn't report:
```
[+] /projects/wind/wind-testing/spack/opt/spack/linux-rhel7-x86_64/gcc-9.3.0/nalu-wind-nightly-master-msofe6wvcalpwvkzbrhh67f25bsd7lbq
```
I also don't see any build errors reported.  This leads me to believe that a build error being trapped is not the issue.

**Comment by tasmith4** [comment]
Looking for differences between running with trap and without, with trap, the `test-exawind-YYYY-MM-DD.log` file contains this line at the very end, which is not present in the run without trap:
```
/projects/wind/wind-testing/scripts/exawind-tests-script.sh: line 1: kill: (-71105) - No such process
```
Conversely, this line (which comes right after the `exawind-tests-script.sh` launch) appears without trap but not with trap in `last-exawind-test-script-invocation.txt`:
```
Done at Sat Mar 12 10:37:39 MST 2022
```

**Comment by psakievich** [comment]
This is interesting. So we're trying to kill a process that doesn't exist anymore? And yes that's the reason for that loop.

**Comment by jrood-nrel** [comment]
The trap command is a little heavy handed. I'm not totally convinced this is stopping submission, but I will look into making it less aggressive and see if that helps.

**Comment by tasmith4** [comment]
@jrood-nrel I think you are right that this is actually not stopping submission, since results haven't returned from ascicgpu for the last couple nights even though I left my modified script (without trap) in the cronjob.

However, running without the trap command does cause the output to appear correctly, as noted in my comment above, so perhaps making it less aggressive will help that aspect.

**Comment by tasmith4** [comment]
This is confirmed not to be the issue blocking submissions to CDash
