### ISSUE TITLE
Get usable binaries from nighly testing

### ISSUE THREAD

**Issue by psakievich** [sandialabs/spack-manager#25]
We want usable binaries in a view from nightly testing. We can keep going the current way of custom packages or possibly explore spack pipelines.

**Comment by jrood-nrel** [comment]
I will look into this to see how to get the top-level tested binaries to install from the nightly packages. I've looked at this before, but I remember it not being trivial.

**Comment by psakievich** [comment]
Okay great! Yes I think this will be complicated, but it will also close the loop on our testing feeding developer and analyst workflows.
