### ISSUE TITLE
Should we add upstreams to the machine configs?

### ISSUE THREAD

**Issue by psakievich** [sandialabs/spack-manager#256]
https://github.com/spack/spack/pull/29680 makes it so we can add upstreams in our spack.yaml/include.yaml files.  So what do you guys think about adding upstreams as part of the standard confgis? Do we want to go that route or only use externals?
@tasmith4 @jrood-nrel

**Comment by tasmith4** [comment]
Can you outline the pros and cons of upstreams vs externals?  My initial reaction is to suspect that upstreams are always active if placed in the configs, taking away the choice between using externals or using a local build, and it seems like choices are good.  But maybe thinking upstreams would take away choice is coming from my ignorance?

**Comment by psakievich** [comment]
Upstreams will make it so those builds are available as read only (i.e. users can't uninstall them).  This would mean that people could link against and avoid a lot of rebuilding when they start out.  Externals will always take precedent over upstreams.  I guess the main con I see to upstreams is it is yet another dependency and thing we may need to explain to people.

**Comment by tasmith4** [comment]
So I thought externals were also read-only, and allow people to link against and avoid rebuilding when starting out?  It's not obvious to me what upstreams do that the externals don't already do

**Comment by tasmith4** [comment]
I think the con is not such a big con if we get rid of the externals, so that we only have one thing to explain

**Comment by psakievich** [comment]
Upstreams and externals essentially do the same thing.  I guess to be more clear on pro's and cons I would say upstreams are extending you database of installs to include everything in the upstreamed spack instance.  The pro is that spack will fully resolve all dependencies and you get all the packages that are installed in the upstream. The con is you more or less have to rely on the concretizer to pick the correct package for you.  

Externals give you specific control of what installations you want, and you force spack to only use those.  The cons here are the loss of information since the full installation information isn't in the spack database anymore.  

I think we should add upstreams into one or two machines to start, and have some or our more experienced users play around with it and the `--reuse` flag.

**Comment by tasmith4** [comment]
even with an upstream and `--reuse`, you can still force a particular version with `^mypackage@version`, right?

**Comment by psakievich** [comment]
You can force a version but not a particular install. A given upstream could have 4-5 instances of `hypre@develop`. The hash may change so you could always pick it by hash, but this is the primary reason we came up with snapshots. Versions are really only useful for releases and we have 4-5 packages in the stack that always have to use the develop version.

**Comment by jrood-nrel** [comment]
I don't think I would bother with upstreams yet with all the work put into externals.
