### ISSUE TITLE
HDF5 and ZFP support for AMR-Wind

### ISSUE THREAD

**Issue by rybchuk** [sandialabs/spack-manager#281]
Hi folks, I'm new to Spack so apologies if this isn't the appropriate forum for this question. AMR-Wind recently [added](https://github.com/Exawind/amr-wind/pull/616) support for ZFP compression of Plotfiles written with HDF5. In order to do this, I believe I need to build AMR-Wind with both HDF5 and ZFP. All of these can be found on Spack, but neither `hdf5` or `zfp` are set as possible variants when building `amrwind`. How would I go about compiling AMR-Wind with support for these libraries?

**Comment by psakievich** [comment]
There is a PR in progress for this. See #277. If you want to test locally then you can pull or cherry pick from there. I think @jrood-nrel wanted to tie up a few loose ends before merging though.
