### ISSUE TITLE
Python module error with `spack -h`

### ISSUE THREAD

**Issue by psakievich** [sandialabs/spack-manager#285]
@jhux2 found this error on summit today:
```console
# spack -h
==> Error: Command module spack.extensions.scripting.cmd.manager_utils (/Users/psakiev/tmp/spack-manager/spack-scripting/scripting/cmd/manager_utils.py) must define function 'manager_utils'.
```

I was able to reproduce on summit and my laptop.  I suspect something has changed with how we are using the functions in `manager_utils` but I'm not positive yet.

**Comment by psakievich** [comment]
It turns out that this is not an error for any command other than `spack -h` making it a much lower priority. @jhux2 can you confirm this on your end?

**Comment by jhux2** [comment]
@psakievich I was able to successfully build naluX on Summit with `spack-manager`.  Thanks for your help today.
