### ISSUE TITLE
Question: can spack-manager use already-installed libraries instead of building from source?

### ISSUE THREAD

**Issue by jhux2** [sandialabs/spack-manager#291]
On Sandia machines, is it possible for spack-manager to use already installed libraries, such as those provided by SEMS?  Or maybe someone has already built a bunch of the prerequisite TPLs and installed them in a project area?  I've got a build going on an ascicgpu machine, and everything is getting built from source.

**Comment by psakievich** [comment]
@jhux2 as an FYI I've got on my to do list to upstream ASC-DevOps' spack instances for all their TPL's. I plan to test that later this week.
