### ISSUE TITLE
Space when specifying compiler

### ISSUE THREAD

**Issue by rybchuk** [sandialabs/spack-manager#294]
In older versions of spack-manager, it was possible to specify the compiler version by including a space before the compiler specification, e.g. `nalu-wind@master+hypre+cuda cuda_arch=70 %gcc` from the documentation [here](https://psakievich.github.io/spack-manager/user_profiles/developers/snapshot_workflow.html). I tried doing so today with the current version of spack-manager and hit an error:

```
$ quick-create-dev -d /projects/awaken/orybchuk/spack-hdf5 -s openfast@2.6.0 %gcc@8.4.0 amr-wind@main+openfast+hdf5 %gcc@8.4.0
+ spack-start
+ spack manager create-dev-env -d /projects/awaken/orybchuk/spack-hdf5 -s [openfast@2.6.0](mailto:openfast@2.6.0) [%gcc@8.4.0](mailto:%gcc@8.4.0) amr-wind@main+openfast+hdf5 [%gcc@8.4.0](mailto:%gcc@8.4.0)
==> Warning: included configuration files should be updated manually [files=include.yaml]
==> Created environment in /projects/awaken/orybchuk/spack-hdf5
==> You can activate this environment with:
==>   spack env activate /projects/awaken/orybchuk/spack-hdf5
==> Error: cannot add anonymous specs to an environment!
 
ERROR: Exiting quick-create prematurely
```

**Comment by psakievich** [comment]
I'm also seeing this trying to concretize with any spaces `exawind+cuda cuda_arch=70` is failing.  Need to fix this asap.
