### ISSUE TITLE
Submodules of spack-manager don't get updated by nightly testing scripts

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#297]
@psakievich #290 has broken the SNL nightly testing, it is dying with errors like `==> Error: /projects/wind/wind-testing-cpu/env-templates/exawind_ascic_tests.yaml:2: Additional properties are not allowed ('concretizer' was unexpected)`.  Although I just noticed this (I hadn't been paying attention to the dates associated with each build), this has in fact been failing since #290 merged.

Do you know what is going on here?  Is it possible the issue is with the repos that are setup for the nightly testing?

**Comment by psakievich** [comment]
@tasmith4 most likely the spack submodule just needs to be updated

**Comment by tasmith4** [comment]
wow ok that's subtle.  I was initially confused because I was sure we were updating the submodules with our scripts.  Turns out the `git clean -df` step fails to remove a file, which causes the `git submodule update` not to run.  See https://github.com/psakievich/spack-manager/blob/141d14883a075da07883845c265b3ddc425aa28e/scripts/update-spack-manager-repo.sh#L16

@jrood-nrel do you have any thoughts on the best way of fixing this?  Can we allow the script to proceed if the clean step fails, or do we need to block on that?  If the latter, is there a way to keep it from choking on the .nfs file that we probably have no control over?

Content of `last-spack-manager-repo-update.txt`:
```
Job is running on ascic178

Run at Thu Jun  2 22:00:02 MDT 2022

Updating spack-manager repo...
+ pwd
/projects/wind/wind-testing-cpu
+ git fetch --all
Fetching origin
+ git reset --hard origin/main
Checking out files: 100% (154/154), done.
HEAD is now at 2e1b569 Update to latest Spack to solve problems with pigz and zlib. Also uninstall dependents for trilinos and hypre during tests. (#292)
+ git clean -df
warning: failed to remove scripts/.nfs8050113e00634366000e8b78
Removing scripts/exawind-tests-script.sh
```

**Comment by jrood-nrel** [comment]
I think it's fine if we change the `&&`s to `;`. Although something holding an NFS lock on that filesystem is a symptom of something external to spack-manager.
