### ISSUE TITLE
Updated spack has broken nightlies

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#325]
After #323, all SNL nightlies are failing with the following lines in the log:

```
Concretizing environment...
+ spack concretize -f
==> Starting concretization pool with 5 processes
==> Error: errors occurred during concretization of the environment:
Package 'armpl' not found.
Package 'armpl' not found.
Package 'armpl' not found.
Package 'armpl' not found.
Package 'armpl' not found.
```

Presumably something changed with how our packages concretize in the newer spack, although it's unclear to me whether it's a spack packaging bug or a weird interaction between the concretizer and our system-specific configs.

@psakievich can you take a look?  Seems like we might want to revert #323 unless this is really easy to fix.

FYI @jrood-nrel, looks like this may also be affecting NREL nightlies.

**Comment by psakievich** [comment]
Run `sm-clean`

This should probably become part of the nightly test process.

**Comment by jrood-nrel** [comment]
Yeah I would be fine adding this to the testing process.

**Comment by jrood-nrel** [comment]
`sm-clean` didn't solve this for me. I manually removed stuff so we'll see if that fixes it.

**Comment by psakievich** [comment]
What did you have to remove? should we update `sm-clean`? I'd like the command to evolve into the big hammer that we use to smash all these types of problems.  We can add options to reduce the heavy handedness at some point down the road.

**Comment by jrood-nrel** [comment]
I removed `.cache` manually. I don't know if that fixes it yet.

**Comment by jrood-nrel** [comment]
Cleaning `.cache` myself seems to have solved it.

**Comment by psakievich** [comment]
I ran into this as well last night and that did it for me too.
