### ISSUE TITLE
OpenFAST compilation on Summit

### ISSUE THREAD

**Issue by lawrenceccheung** [sandialabs/spack-manager#345]
I'm using the default Summit configuration to try and compile an OpenFAST-coupled AMR-Wind executable.  The error I get is related to the HDF5 high level libraries during the OpenFAST CMake process, notably related to the `HDF5_HL_LIBRARIES` define:
```
  >> 36    CMake Error at /autofs/nccs-svm1_sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/cmake-3.21.3-7st3jbsm6qhqw4hoysgdbpw6buts
           ljtp/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     37      Could NOT find HDF5 (missing: HDF5_HL_LIBRARIES)
```

The problem goes away if I comment out this line in the openfast `package.py` file:
https://github.com/psakievich/spack-manager/blob/55e85606fcb4d865055117dfb03bbb351d017100/repos/exawind/packages/openfast/package.py#L17

The default hdf5 `1.10.7` module on Summit works fine otherwise, no other changes needed.

Lawrence

**Comment by psakievich** [comment]
This is strange since we use `1.10.7` on almost every system.  @jrood-nrel you spent a lot of time on this. We can do an exception based on the summit machine, but I wonder if there is something more specific related to the installation we can trigger on.

**Comment by jrood-nrel** [comment]
I compile everything on Summit regularly and I don't see this issue.

**Comment by jrood-nrel** [comment]
Oops, openfast isn't enabled by default, so my last statement is false. I will look into this.

**Comment by jrood-nrel** [comment]
Not sure when I will get to this. The first thing I would try is commenting out these lines https://github.com/psakievich/spack-manager/blob/55e85606fcb4d865055117dfb03bbb351d017100/configs/summit/packages.yaml#L32-L36

**Comment by lawrenceccheung** [comment]
Yeah, I tried modifying/commenting out the `hdf5` section or parts of it so that it would download and build `hdf5` during install.  That didn't change anything.  Neither forcing a define of `HDF5_HL_LIBRARIES` in during OpenFAST's cmake.

Lawrence

**Comment by psakievich** [comment]
@lawrenceccheung did you modify those lines with an active environment?  If so they need to be modified in the `include.yaml` file not in the spack-manager repo.  Those are just referenced when we create the environment to populate the `include.yaml`

**Comment by lawrenceccheung** [comment]
yeah, I did it both ways, editing the `configs/summit/packages.yaml` before activating any spack environment, and also modifying the `include.yaml` after the environment was already created.  It was the same error either way,

**Comment by psakievich** [comment]
Well the real question is when you commented those out did hdf5 build and then you still got these errors, or did it still use the external? Unfortunately there are a few ways that the external hdf5 could have persisted in a second attempt. 

If it still failed when building hdf5 from scratch then it is a slightly different problem.
