### ISSUE TITLE
Nightly testing dies at spack-start

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#355]
@psakievich

At SNL, both the CPU and GPU nightly test scripts die without printing anything, right after spack-start.  Output from `last-exawind-test-script-invocation.txt`:
```
Starting at Thu Sep 22 22:00:23 MDT 2022.

SPACK_MANAGER set to /projects/wind/wind-testing-cpu

SPACK_MANAGER_GOLDS_DIR set to /projects/wind/golds-cpu

Activating Spack-Manager...
+ source /projects/wind/wind-testing-cpu/start.sh && spack-start
```

It's not immediately clear to me why this is, since the only PR to merge since the last successful nightly run is #354, which shouldn't affect anything to do with startup.

@jrood-nrel it looks as if the NREL nightlies didn't run last night either, did you experience the same issue?

**Comment by jrood-nrel** [comment]
I think it's #351

**Comment by tasmith4** [comment]
@jrood-nrel that was my first guess, but that PR merged in the middle of the day Sep. 21, and the nightlies still ran the night of Sep. 21/22.  Wouldn't that rule it out?

**Comment by tasmith4** [comment]
I take that back.  Could be a bug that only shows up on the second run

**Comment by psakievich** [comment]
I'll be in later to take a look. Feel free to revert the commit if that helps

**Comment by tasmith4** [comment]
@psakievich I think we can hold off on reverting unless we don't figure it out today.  Probably though, the issue is that `spack repo add` chokes if the repo is already added, in contrast to my belief about how it should work after reading the docs.

**Comment by jrood-nrel** [comment]
We should revert it.

**Comment by psakievich** [comment]
I'll take care of this today. Have either of you confirmed that commit is the issue?

**Comment by jrood-nrel** [comment]
It caused problems for me on Crusher yesterday in the same manner Timothy described, so I assume this is problem with the dashboard. Since it's set to `/dev/null` it doesn't output anything.
