### ISSUE TITLE
Kokkos can't find devices through MPICH

### ISSUE THREAD

**Issue by psakievich** [sandialabs/spack-manager#365]
I learned through experience today that using MPICH is dramatically slowing our tests down on ascicgpu.  Kokkos can only manage mpi device allocations through openmpi, slurm and mvapich.  I think this is a compelling reason to switch back to openmpi on any device enabled machine where we are building our own mpi.  @tasmith4 @jrood-nrel 

For example the `convTaylorVortex` test in nalu-wind takes ~40 sec on eagle, but ~500-600 sec on ascicgpu.

**Comment by psakievich** [comment]
@jrood-nrel this could also explain why my test cases are running so slow with the hybrid solver on device.

**Comment by jrood-nrel** [comment]
Can you only use openmpi on ascicgpu? I can't agree to going back to openmpi.

**Comment by psakievich** [comment]
Yeah that is fine.  I don't see why we need a global decision on this.  On most platforms openmpi it is already built. That is the nvidia default that they ship with from what I've been reading. I'm trying to see what I need to do to get the prebuilt ones to work.  There is also `mvapich2` which is probably the happy middle ground.

**Comment by tasmith4** [comment]
I agree that we don't need a global decision on this.  I think this is part of the advantage/purpose of spack/spack-manager, to take advantage of the best software setups on different platforms.

**Comment by psakievich** [comment]
#445 Should allow us to close this after nightly testing confirmation.
