### ISSUE TITLE
Consolidate builtin and exawind nalu-wind packages

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#372]
Currently, there's quite a bit of logic in the `exawind.nalu-wind` package that really should belong in `builtin.nalu-wind`.  Most of it is HIP/ROCm stuff, which we've been actively developing and is easier to work with in Spack-Manager.  This is probably still appropriate as we continue to work through getting setup on HIP platforms.  Starting this issue as a reminder to us that eventually we should consolidate these packages and upstream most of the stuff to mainline spack.

@jrood-nrel @psakievich

**Comment by psakievich** [comment]
Yeah we are due for a large scale upstreaming of our package changes. Thanks for adding an issue @tasmith4!
