### ISSUE TITLE
Build on M1 Mac fails with default spec but passes using a similar spec

### ISSUE THREAD

**Issue by moprak-nrel** [sandialabs/spack-manager#470]
When creating an env with `quick-create -n exawind -s exawind@master` the build fails on my M1 Mac, and the DAG is [failing-dag.txt](https://github.com/sandialabs/spack-manager/files/10290756/failing-dag.txt).  However, if the spec is slightly changed to `exawind@master+hypre+ninja~openfast` the build succeeds and the DAG is [successful-dag.txt](https://github.com/sandialabs/spack-manager/files/10290757/successful-dag.txt). A surprising difference between the two DAGs is the mpich version, the failing one has  `mpich 3.4.3` vs `mpich 4.0.2` in the successful build.
The build failure is however from `libquadmath` errors while building `hypre` and `trilinos`, and I'm not sure if the mpich version has anything to do with it.

**Comment by psakievich** [comment]
Closing this here. Please migrate to https://github.com/exawind/exawind-manager if the issue still persists
