### ISSUE TITLE
Latest spack refactors Environment

### ISSUE THREAD

**Issue by frobnitzem** [sandialabs/spack-manager#528]
Since [April 14](https://github.com/spack/spack/pull/36927) the following lines are causing issues when updating spack to the latest develop:

https://github.com/sandialabs/spack-manager/blob/485cc7ef214ce40521ad3ab697986f82d1f524bf/spack-scripting/scripting/cmd/manager_cmds/create_env.py#L49-L105

Perhaps some input from the spack team could help re-write them.

**Comment by psakievich** [comment]
Do you have an example of the issue or a stack trace? I haven't been working off the latest develop, but I can take a look.

**Comment by psakievich** [comment]
I see what happened. They removed the option to create from a file and now set it as a directory: https://github.com/spack/spack/blob/730ab1574fffd95b5a55f91bb243d477b104695f/lib/spack/spack/environment/environment.py#L761

**Comment by psakievich** [comment]
@frobnitzem FYI this has only been active on develop for 7 days. I probably can't really fix this until next week, hopefully you can roll back spack to the commit before this went in.  There are several things we want to get from an updated spack so I will try to get to this as soon as I can and just update the submodule at the same time.

**Comment by frobnitzem** [comment]
Yes, I rolled back. I think the changes to spack are large enough, it would
be good to ask them what to do here.

**Comment by psakievich** [comment]
@frobnitzem there is another bug at the tip of `spack@develop` so the current submodule is 1-2 days back. I will update again when that bug is addressed. The spack team is aware of it and it may get fixed as part of their 0.20 release
