### ISSUE TITLE
Spack "upstream not found" warning

### ISSUE THREAD

**Issue by wyphan** [sandialabs/spack-manager#571]
Creating an Exawind snapshot on a freshly-cloned `spack-manager` makes Spack emit this warning:

```plain
==> Warning: upstream not found: /path/to/spack-manager/spack/opt/spack/.spack-db/index.json
```

Normally this warning is harmless, but for container builds, it makes Spack return an error code of 2, which terminates the container build process early. Regardless, the warning is actually valid, since with a fresh clone, no Spack packages have been installed yet, and such the upstream Spack database doesn't exist.

There are two ways to fix this:
- Skip setting up the upstream entirely
- Install a package in upstream before running the create snapshot script

**Comment by psakievich** [comment]
We will have to migrate this to exawind-manager if it resurfaces
