### ISSUE TITLE
AMR-Wind failed to build

### ISSUE THREAD

**Issue by JarredK21** [sandialabs/spack-manager#579]
Hi,

I am having issues building AMR-Wind using Spack-manager on NREL's Kestrel. 
I followed the instructions to build amr-wind but I am still having errors, specifically when it is trying to build netcdf, hdf5 and hypre.
I have attached the errors in a text file.

[Building amr-wind errors.txt](https://github.com/sandialabs/spack-manager/files/13490526/Building.amr-wind.errors.txt)

Kind regards,

Jarred

**Comment by psakievich** [comment]
@JarredK21 has this issue been resolved for you?

**Comment by psakievich** [comment]
Closing this here. Please migrate to https://github.com/exawind/exawind-manager if the issue still persists
